services:
  backend:
    build:
      context: ./backend # Dockerfile があるサブディレクトリ
      dockerfile: Dockerfile # Dockerfileのファイル名を明示
    container_name: chasaji-backend
    working_dir: /app
    volumes:
      - ./backend/:/app
    ports:
      - "8000:8000"
    command: tail -f /dev/null # 起動時に即時終了を防ぐコマンド

  db:
    image: postgres:14.17
    container_name: chasaji-db
    environment:
      POSTGRES_DB: learn
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: sajisaji
    ports:
      - "5432:5432"
    volumes:
      - ./db/init:/docker-entrypoint-initdb.d
      - postgres-data:/var/lib/postgresql/data

volumes:
  postgres-data:
    driver: local


