FROM amazonlinux:2

RUN amazon-linux-extras install postgresql14

# docker build -t python-http .      # イメージをビルド
# コンテナを起動（どっちか）
# docker run -p 8000:8000 python-http # フォアグラウンドで起動
# docker run -d -p 8000:8000 python-http # バックグラウンドで起動

# docker-compose up --build -d

# コンテナに入る
# docker ps
# docker exec -it <CONTINER ID or NAMES> bash
