# .github/workflows/deploy-backend.yml
name: Deploy Backend to EC2

on:
  workflow_run:
    workflows: ["CI"]      # CI ワークフローの name と合わせる
    types:
      - completed

jobs:
  deploy-backend:
    name: Deploy Python Backend to EC2
    runs-on: ubuntu-latest
    # main ブランチかつ CI 成功時のみ
    if: ${{ github.event.workflow_run.conclusion == 'success' && github.event.workflow_run.head_branch == 'main' }}

    steps:
      - name: リポジトリをチェックアウト
        uses: actions/checkout@v4

      - name: EC2 へ同期＆リモートコマンド実行
        uses: appleboy/ssh-action@v0.1.6
        with:
          host: ${{ secrets.EC2_HOST }}         # 例: 52.11.22.33
          username: ${{ secrets.EC2_USER }}     # 例: ubuntu
          key: ${{ secrets.EC2_SSH_KEY }}       # 秘密鍵 (PEM 形式)
          port: 22
          # サーバ起動スクリプトの実行
          script: |
            cd /home/ec2-user/aws-learn/backend
            git pull origin main 2>&1
            pip3 install -r requirements.txt
            # root 権限で nohup を起動し、バックグラウンド化
            sudo nohup python3 -m uvicorn main:app --host 0.0.0.0 --port 80 --reload > uvicorn.log 2>&1 &
            echo "out put uvicorn.log"
            cat uvicorn.log
            echo "------fin------"